import { IApiConfig, IDualApiConfig } from "../core/context";
import { FieldType, PropertyType } from "../core/types/field-types";
import type { Template, VisibilityConfig, IFieldTypeProperties } from "../core/types";
import { IModalConfig } from "../modal/Modal";
import type { IRelationFieldConfig } from "./renderers/RelationFieldRenderer";
import { ISectionsConfig } from "../pages/PostAuth/SectionsRenderer";
import type { IEntityConfigReference } from "../core/hooks/useEntityConfig";
type ITablePagination = "default";

/**
 * Expandable row configuration for tables.
 * 
 * Matches backend type from fw24/src/entity/base-entity.ts (ITableExpandableConfig)
 */
export interface ITableExpandableConfig {
  mode: 'nested-table' | 'details' | 'custom' | 'json';
  relationField?: string;
  tableConfig?: {
    apiUrl: string;
    apiMethod?: 'GET' | 'POST';
    responseKey?: string;
    columns?: ReadonlyArray<string> | Array<string>;
    pageSize?: number;
    showPagination?: boolean;
    defaultFilters?: ITableFilters;
    showViewAll?: boolean;
    viewAllModalWidth?: number | string;
  };
  detailsConfig?: {
    fields?: ReadonlyArray<string> | Array<string>;
    numColumns?: number;
  };
  customConfig?: {
    pageType: 'list' | 'details' | 'form' | 'dashboard' | 'accordion';
    pageConfig?: ITableFilters;
  };
  rowExpandable?: VisibilityConfig;
  defaultExpanded?: boolean;
  expandIcon?: string;
  indentSize?: number;
}

/**
 * Type-safe filter values.
 * Used in defaultFilters and filter state.
 */
export interface ITableFilters {
  readonly [ key: string ]: string | number | boolean | null | undefined |
  ReadonlyArray<string | number | boolean | null>;
}


/**
 * Sort configuration for tables
 * 
 * Used in both backend (entity schema) and frontend (UI config)
 * 
 * Three formats supported:
 * 
 * 1. Object (single column sort for search):
 *    { field: 'createdAt', order: 'desc' }
 * 
 * 2. Array (multi-column sort for search):
 *    [{ field: 'publishDate', order: 'desc' }, { field: 'likeCount', order: 'desc' }]
 * 
 * 3. Order string (DynamoDB index order indication):
 *    'asc' | 'desc'
 *    Note: For DynamoDB, this indicates the expected index order direction,
 *    not an actual sort parameter (DynamoDB returns data in index PK/SK order)
 */
export type SortConfig =
  | { field: string; order: 'asc' | 'desc' }           // Single column sort (search mode)
  | Array<{ field: string; order: 'asc' | 'desc' }>    // Multi-column sort (search mode)
  | 'asc' | 'desc';                                     // Index order direction (DynamoDB mode)

/**
 * Extended IApiConfig for table use with defaultSort
 */
export interface ITableApiConfig extends IApiConfig {
  defaultSort?: SortConfig;
}

/**
 * Extended IDualApiConfig for table use with defaultSort
 */
export interface IDualTableApiConfig {
  search: ITableApiConfig;
  database: ITableApiConfig;
}

/**
 * Table configuration interface
 * 
 * For single endpoint (backward compatible):
 * ```typescript
 * {
 *   apiConfig: {
 *     apiUrl: "/api/posts",
 *     apiMethod: "GET",
 *     useSearch: true // or false
 *     defaultSort: { field: 'createdAt', order: 'desc' }
 *   }
 * }
 * ```
 * 
 * For dual endpoints (search + database):
 * ```typescript
 * {
 *   apiConfig: {
 *     search: {
 *       apiUrl: "/api/search/posts",
 *       apiMethod: "GET",
 *       responseKey: "items",
 *       defaultSort: [{ field: 'publishDate', order: 'desc' }]
 *     },
 *     database: {
 *       apiUrl: "/api/posts",
 *       apiMethod: "GET",
 *       responseKey: "data",
 *       defaultSort: 'desc'  // DynamoDB index order
 *     }
 *   }
 * }
 * ```
 */

/**
 * Filter segment (quick filter tab) configuration.
 * Matches backend type from fw24/src/entity/base-entity.ts (IFilterSegment)
 */
export interface IFilterSegment {
  id: string;
  label: string;
  icon?: string;
  filters: Record<string, any>;
  default?: boolean;
  visibility?: VisibilityConfig;
  badge?: number | string;
  badgeStatus?: 'success' | 'processing' | 'error' | 'warning' | 'default';
}

/**
 * Filter segment group configuration.
 * Groups related segments together with a label (e.g., "By Status", "By League").
 * Each group manages its own filter state independently.
 * Matches backend type from fw24/src/entity/base-entity.ts (IFilterSegmentGroup)
 */
export interface IFilterSegmentGroup {
  id: string;
  label: string;
  segments: IFilterSegment[];
  defaultSegmentId?: string;
  maxVisible?: number;
}

/**
 * Table configuration interface.
 * Generated by FW24 backend from entity schema.
 * 
 * Row actions are merged into propertiesConfig[identifier].actions
 * Bulk actions come from entitySchema.model.listPageConfig.tableConfig.bulkActions
 * Row selection comes from entitySchema.model.listPageConfig.tableConfig.rowSelection
 */
export interface ITableConfig {
  propertiesConfig: Array<ITablePropertiesConfig>;
  apiConfig: ITableApiConfig | IDualTableApiConfig;
  records?: Array<any>;
  paginationType?: ITablePagination;
  routeParams?: Record<string, any>;
  defaultFilters?: Record<string, any>; // Pre-applied filters (supports placeholders like ":teamId")
  entityName?: string;  // Entity name from backend config generation
  bulkActions?: ReadonlyArray<IPageAction>;  // Actions shown when multiple rows selected (from backend tableConfig.bulkActions)
  rowSelection?: {
    readonly enabled: boolean;
    /** Selection type: 'checkbox' for multi-select, 'radio' for single-select */
    readonly type?: 'checkbox' | 'radio';
    readonly visibility?: VisibilityConfig;  // Conditional row selection
  };  // Row selection configuration (from backend tableConfig.rowSelection)
  /**
   * Expandable row configuration.
   * From backend: entitySchema.model.listPageConfig.tableConfig.expandable
   * 
   * Allows displaying nested data (e.g., to-many relations) within table rows.
   * Uses existing Table component for nested-table mode, providing full table features.
   */
  expandableConfig?: ITableExpandableConfig;

  /**
   * Filter segments (quick filter tabs).
   * From backend: entitySchema.model.listPageConfig.tableConfig.segments
   * 
   * Supports two formats:
   * 1. Flat array (legacy): Single group of segments
   * 2. Grouped array: Multiple independent segment groups
   * 
   * Displayed as tabs above the table for quick access to common filter sets.
   * Supports placeholder resolution (`:actor.actorId`, `:startOfToday`, etc.)
   * 
   * Segment selection is reactive: UI automatically updates when filters change from any source
   * (URL, column filters, applied filters removal, or segment clicks).
   */
  segments?: Array<IFilterSegment | IFilterSegmentGroup>;

  /**
   * Controls how column data is fetched from the API.
   * From backend: entitySchema.model.listPageConfig.tableConfig.fetchStrategy
   * 
   * - `'eager'` (default): Fetches all `isListable` columns in a single request.
   * - `'lazy'`: Only fetches visible columns initially. Refetches when users show hidden columns.
   * 
   * @default 'eager'
   */
  fetchStrategy?: 'eager' | 'lazy';

  /**
   * Default number of records per page.
   * From backend: entitySchema.model.listPageConfig.tableConfig.pageSize
   * 
   * Users can change this via the pagination controls (options: 10, 20, 50, 100).
   * 
   * @default 10
   */
  pageSize?: number;

  /**
   * Additional sections to display below or alongside the main table.
   * From backend: entitySchema.model.listPageConfig.sectionsConfig
   * 
   * Enables multi-section list pages with tabs or accordion UI.
   * Sections have access to table state (selected records, filters) via routeParams.
   */
  sectionsConfig?: ISectionsConfig;

  onDataChange?: (data: {
    selectedRecords?: ReadonlyArray<Record<string, unknown>>;
    filters?: ITableFilters;
    searchQuery?: string;
    pageType?: string;
    entityName?: string;
    selectedRowKeys?: ReadonlyArray<React.Key>;
  }) => void;
}

export interface ITablePropertiesConfig extends IFieldTypeProperties {
  name: string;
  dataIndex: string;
  actions?: Array<IPageAction>;
  hidden?: boolean;
  /**
   * Controls initial visibility of the column in list pages.
   * - true: Column is visible by default
   * - false: Column is hidden by default but available in Column Settings
   * - undefined: Falls back to !hidden for backward compatibility
   * From backend: tableConfig.columns[].defaultVisible
   */
  defaultVisible?: boolean;
  isFilterable?: boolean;
  isIdentifier?: boolean;
  isSortable?: boolean;
  fieldType?: FieldType;
  type?: PropertyType;  // Data type from entity schema (list, map, object)
  placeholder?: string;
  helpText?: string;
  /**
   * Group title for column grouping.
   * Columns with the same groupTitle will be grouped under a common header.
   * From backend: tableConfig.columns[].groupTitle
   */
  groupTitle?: string;

  /**
   * Template for rendering column values.
   * Supports nested paths and composite templates.
   * If provided, overrides default rendering.
   * 
   * @example
   * // Simple string template
   * template: '{firstName} {lastName}'
   * 
   * @example
   * // Complex template with nested paths
   * template: {
   *   composite: ['jerseyNumber', 'name', 'team.name'],
   *   template: '#{jerseyNumber} {name} ({team.name})'
   * }
   */
  template?: Template;

  /**
   * Custom renderer key for this field/column.
   * When specified, the frontend uses this key to look up a registered custom renderer
   * via ExtensionRegistry.getFieldRenderer() or getColumnRenderer().
   * 
   * @example
   * renderer: 'address-picker'
   */
  renderer?: string;

  /**
   * Configuration passed to the custom renderer.
   * Only used when `renderer` is specified.
   */
  rendererConfig?: Readonly<Record<string, unknown>>;

  /**
   * Relation field configuration for rendering related entities.
   * 
   * When present, this column will be rendered using RelationFieldRenderer
   * instead of the standard template renderer, providing:
   * - Template-based display using duplicated relation data
   * - Fallback templates for ID-only data
   * - Links to related entities
   * - Modal viewing with lazy config resolution
   * - Custom actions
   * 
   * Priority: relationConfig > template > fieldType-based rendering
   * 
   * Backend auto-generates this from entity relation definitions.
   * 
   * @example
   * // To-one relation (team field showing team name with link/modal)
   * relationConfig: {
   *   routePattern: '/view-team/:teamId',
   *   identifierMapping: { source: 'teamId', target: 'teamId' },
   *   modalConfigRef: { entityName: 'team', pageType: 'view' },
   *   displayConfig: {
   *     template: '{teamName}',
   *     fallback: { template: 'Team: {teamId}' }
   *   }
   * }
   * 
   * @example
   * // To-many relation (games field showing count with modal list)
   * relationConfig: {
   *   routePattern: '/list-game',
   *   modalConfigRef: {
   *     entityName: 'game',
   *     pageType: 'list',
   *     overrideConfig: { defaultFilters: { teamId: ':teamId' } }
   *   },
   *   displayConfig: {
   *     showLink: false,
   *     showModalIcon: true
   *   }
   * }
   */
  relationConfig?: IRelationFieldConfig;

  // Filter configuration options
  filterConfig?: {
    defaultOperator?: string; // Default filter operator (e.g., 'contains', 'eq', 'in')
    availableOperators?: string[]; // Restrict available operators for this column
    predefinedOptions?: Array<{ label: string; value: string }>; // For dropdown/select filters
    filterType?: 'text' | 'select' | 'datetime' | 'number' | 'boolean'; // Filter input type
  };
}

/**
 * Page action type
 * Supports buttons, dropdowns with modals/navigation
 * Note: items cannot have nested items (max 1 level of nesting)
 */
/**
 * Page action type
 * Supports buttons, dropdowns, modals, and navigation
 * 
 * Patterns:
 * 1. Navigation: { url: "/view-user/:id" }
 * 2. Modal with inline config: { openInModal: true, modalConfig: {...} }
 * 3. Modal with route resolution: { openInModal: true, url: "/view-user/:id" }
 */
export type IPageAction = {

  id?: string;

  label: string;

  /**
   * Dynamic label template (evaluated from routeParams or record context).
   * If provided, overrides static `label` field.
   * Can be a simple string like '{teamName}' or complex object.
   */
  template?: Template;

  /**
   * Tooltip text (shown on hover).
   * Can be static string or dynamic template evaluated from routeParams/record context.
   * 
   * @example
   * // Static tooltip
   * tooltip: 'View all child spans'
   * 
   * @example
   * // Dynamic tooltip
   * tooltip: 'View trace for {correlationId}'
   * 
   * @example
   * // Complex template
   * tooltip: {
   *   composite: ['teamName', 'status'],
   *   template: 'Edit {teamName} (Status: {status})'
   * }
   */
  tooltip?: Template;

  url?: string;
  icon?: string;
  type?: 'button' | 'dropdown';
  items?: Array<Omit<IPageAction, 'items'>>;  // Items cannot have sub-items

  /** Open action in modal instead of navigating */
  openInModal?: boolean;

  /** Modal configuration (inline config or resolved from url) */
  modalConfig?: IModalConfig;

  /** 
   * Entity config reference for modal route resolution (when using openInModal without modalConfig).
   * Provides overrideConfig support for defaultFilters, hideSegments, etc.
   * Used by OpenRouteInModal component.
   * 
   * @example
   * {
   *   openInModal: true,
   *   modalConfigRef: {
   *     entityName: 'observabilityLog',
   *     pageType: 'list',
   *     overrideConfig: {
   *       defaultFilters: { parentId: ':id' },
   *       hideSegments: ['hierarchy-group']
   *     }
   *   }
   * }
   */
  modalConfigRef?: IEntityConfigReference;

  /** Custom modal width. Default: auto-detect from page type */
  modalWidth?: number | string;

  /** Override resolved page title when opened in modal */
  modalTitle?: string;

  /** Hide this action when rendered inside a modal. Default: false */
  hideInModal?: boolean;

  /** Only open in modal on specified screen size. Default: always */
  openInModalCondition?: 'sm' | 'md' | 'lg' | 'xl';

  // =========================================================================
  // DRAWER SUPPORT
  // =========================================================================

  /** Open action in drawer (slide-out panel) instead of navigating */
  openInDrawer?: boolean;

  /** Drawer configuration (when openInDrawer is true) */
  drawerConfig?: {
    /** Drawer title (supports templates like 'Edit {teamName}') */
    title?: Template;
    /** Drawer placement */
    placement?: 'left' | 'right' | 'top' | 'bottom';
    /** Drawer width (for left/right placement) */
    width?: number | string;
    /** Drawer height (for top/bottom placement) */
    height?: number | string;
    /** Show close button */
    closable?: boolean;
    /** Show mask overlay */
    mask?: boolean;
    /** Close on mask click */
    maskClosable?: boolean;
    /** Destroy content on close */
    destroyOnClose?: boolean;

    // =========================================================================
    // INLINE PAGE CONFIG (for drawers without route resolution)
    // =========================================================================

    /** Page type to render in drawer: 'form', 'details', 'list', etc. */
    drawerType?: 'form' | 'details' | 'list';
    /** Page configuration (form/details/list config) */
    drawerPageConfig?: {
      /** Form/details title */
      title?: string;
      /** Help text shown below title */
      helpText?: string;
      /** Properties/fields to render */
      propertiesConfig?: Array<{
        name: string;
        label: string;
        column?: string;
        fieldType: string;
        required?: boolean;
        placeholder?: string;
        helpText?: string;
        defaultValue?: unknown;
        options?: {
          apiMethod?: string;
          apiUrl?: string;
          responseKey?: string;
          optionMapping?: { label: string; value: string };
          disableSearch?: boolean;
          disableLoadMore?: boolean;
        } | Array<{ label: string; value: string | number }>;
        [ key: string ]: unknown;
      }>;
      /** API configuration for form submission */
      apiConfig?: {
        apiMethod?: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
        apiUrl?: string;
        responseKey?: string;
      };
      /** Form buttons to show */
      formButtons?: Array<'submit' | 'reset' | 'cancel'>;
      /** Response display config */
      responseConfig?: {
        showModal?: boolean;
        modalTitle?: string;
      };
      [ key: string ]: unknown;
    };
  };

  /** Entity config reference for drawer route resolution */
  drawerConfigRef?: IEntityConfigReference;

  /**
   * Visibility configuration for conditional rendering.
   * Controls visibility and enablement based on actor roles, record state, context, and custom logic.
   * Evaluated using the universal evaluation system.
   */
  visibility?: VisibilityConfig;
};

export interface IActionIndexValue {
  [ key: string ]: Array<IPageAction>;
}

export interface IRecord {
  [ key: string ]: string;
}
